[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["lib"]
#libs = ["lib", "contracts/src"]  # Using this - only when installing dependencies. After that, this should be switched to the "libs = ['lib']" above.
script = "contracts/scripts"
test = "contracts/test"
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"


[rpc_endpoints]
#sepolia = "${SEPOLIA_RPC}"
base_testnet = "${BASE_TESTNET_RPC}"